# Problem : Find the Difference
# Problem Statement : You are given two strings s and t.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Return the letter that was added to t.
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        x = 0
        for i in range(len(s)):
            x = x ^ ord(s[i]) ^ ord(t[i])
        x = x ^ ord(t[-1])
        return chr(x)